---
title: "Workshop 3"
author: "Michael Guijt"
date: "2025-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.1 Workshop schedule

Workshop schedule

## 4.2 Workshop Overview

Workshop overview.

## 4.3 Tidying data using Tidyr

Loading tidyverse

## 4.4 Tidy data

Tidying data up/

## 4.5 Pivoting data

### 4.5.1

```{r}
billboard

billboard |> pivot_longer(
  cols = starts_with("wk"),
  names_to = "week",
  values_to = "rank",
  values_drop_na = TRUE
)
```

### 4.5.2

```{r}
df <- tribble(
  ~id, ~bp1, ~bp2,
  "A", 100, 120,
  "B", 140, 115,
  "C", 120, 125
)

df |> 
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
  )
```

### 4.5.3

```{r}
cms_patient_experience

cms_patient_experience |> 
  distinct(measure_cd, measure_title)

cms_patient_experience |> 
  pivot_wider(
    id_cols = starts_with("org"),
    names_from = measure_cd,
    values_from = prf_rate
  )
```

### 4.5.4

```{r}
df <- tribble(
  ~id, ~measurement, ~value,
  "A", "bp1", 100,
  "B", "bp1", 140,
  "B", "bp2", 115,
  "A", "bp2", 120,
  "A", "bp3", 105
)

df |> 
  pivot_wider(
    names_from = measurement,
    values_from = value
  )

df |>
  distinct(measurement) |>
  pull()

df |>
  select(-measurement, -value) |>
  distinct() |>
  mutate(x = NA, y = NA, z = NA)
```

### 4.5.5

1.

```{r}
stocks <- tibble(
  year = c(2015, 2015, 2016, 2016),
  half = c( 1, 2, 1, 2),
  return = c(1.88, 0.59, 0.92, 0.17)
)

#stocks %>% 
#  pivot_wider(names_from = year, values_from = return) %>%
#  pivot_longer('2015':'2016', names_to = "year", value_to = "return") 

```

3. Need to make it longer, the variables are "pregnant," "sex," and "count." 

### 4.5.6

```{r}
table3

table3 %>%
  separate(rate, into = c("cases","population"), sep = "/", convert = TRUE)

table3 %>%
  separate(year, into = c("century","year"), sep = 2)

table5 %>%
  unite(new, century, year, sep="")
```

## 4.6

### 4.6.1

```{r}
treatment <- tribble(
  ~person, ~treatment, ~response,
  "Derrick Whitmore", 1, 7, 
  NA, 2, 10,
  NA, 3, NA, 
  "Katherine Burke", 1, 4
)

treatment |>
  fill(everything())
```

## 4.6.2

```{r}
x <- c(1,4,5,7,NA)
coalesce(x,0)

x <- c(1,4,5,7,-99)
na_if(x, -99)
```

## 4.6.3

```{r}
x <- c(NA, NaN)
x * 10
x == 1
is.na(x)
```

## 4.6.4

```{r}
stocks <- tibble(
  year = c(2020, 2020, 2020, 2020, 2021, 2021, 2021),
  qtr = c(1, 2, 3, 4, 2, 3, 4),
  price = c(1.88, 0.59, 0.35, NA, 0.92, 0.17, 2.66)
)

stocks |>
  pivot_wider(
    names_from = qtr,
    values_from = price
  )
```

## 4.7

### 4.7.1

```{r}
students <- read_csv("https://pos.it/r4ds-students-csv")

students
```

### 4.7.2

```{r}
students <- read.csv("https://pos.it/r4ds-students-csv", na = c("N/A",""))

students
```

## 4.8 Learning relational data

### 4.8.1

```{r}
library(nycflights13)

planes %>%
  count(tailnum) %>%
  filter(n > 1)

weather %>%
  count(year, month, day, hour, origin) %>%
  filter(n > 1)

flights %>%
  count(year, month, day, flight) %>%
  filter(n > 1)
```

### 4.8.2

```{r}
flights2 <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier)

flights2 %>%
  select(-origin, -dest) %>%
  left_join(airlines, by = "carrier")

x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  3, "x3"
)

y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2",
  4, "y3"
)

x %>%
  inner_join(y, by = "key")

x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  2, "x3",
  1, "x4"
)

y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2"
)

left_join(x,y, by = "key")

flights2 %>%
  left_join(planes, by = "tailnum")

flights2 %>%
  left_join(airports, c("dest" = "faa"))
```

## 4.9 Pipes

```{r, eval = FALSE}

#1 
foo_foo_1 <- hop(foo_foo, through = forest)
foo_foo_2 <- scoop(foo_foo_1, up = field_mice)
foo_foo_3 <- bop(foo_foo_2, on = head)

#2
foo_foo <- hop(foo_foo, through = forst)
foo_foo <- scoop(foo_foo, up = field_mice)
foo_foo <- bop(foo_foo, on = head)

#3
bop(
  scoop(
    hop(foo_foo, through = forest),
    up = field_mice
  ),
  on = head
)

#4
foo_foo %>%
  hop(through = forest) %>%
  scoop(up = field_mice) %>%
  bop(on = head)
```








